name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test-jenkins
      - name: Validate
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: validate
