name: CI

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
        env:
          AS_VERSION: ${{ github.ref }}
      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test-jenkins
      - name: Report test results
        uses: ashley-taylor/junit-report-annotations-action@master
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "${{ github.workspace }}/build/test-results/test/*.xml"
        if: always()
      - name: Validate
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: validate
        env:
          AS_VERSION: ${{ github.ref }}
      - name: Prepare publish
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
      - name: Publish
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: pub
        env:
          AS_VERSION: ${{ github.ref }}
